FROM golang:1.24-bookworm

# Update package list
RUN apt-get update

# Install build-essential for CGO
RUN apt-get install -y build-essential

# Clean up apt cache
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy go.mod and go.sum first for caching
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the source code
COPY . .

WORKDIR /app/vpx

CMD ["go", "test", "-v"]
